### ISSUE TITLE
Api gateway question

### ISSUE THREAD

**Issue by vforv** [eoinsha/node-seneca-base#1]
Hello,

I am new to microservices and this repo catch my eye... 

I have question regarding api getway, is in this example as it should look like in production? 

I tought for api gateway it is some dynamic routing....

**Comment by eoinsha** [comment]
I'm not sure exactly what your intention is but in general, Seneca can be used for dynamic routing with an API gateway. I have done this on a few projects.  It might be worth asking about this on the Seneca Gitter (https://gitter.im/senecajs/seneca).
